sudo: false
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
    - "nightly"

matrix:
  fast_finish: true
  include:
    - env: TOXENV=qa
      python: "3.7"

  allow_failures:
    - python: "2.7"
    - env: TOXENV=qa
    - python: "3.9-dev"
    - python: "nightly"


install: pip install tox-travis python-coveralls codecov
script: tox
after_success:
  - codecov -e TOXENV

# TODO
#deploy:
#  provider: pypi
#  user: Apkawa
#  password:
#    # https://docs.travis-ci.com/user/encryption-keys/
#    secure: ''
#  on:
#    tags: true
#    distributions: sdist bdist_wheel
#    repo: Apkawa/pytest-ngrok
#    branch: master
